version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  crawler_file:
    class: logging.FileHandler
    filename: "../logs/crawler.log"
    formatter: simple
    level: DEBUG
  updater_file:
    class: logging.FileHandler
    filename: "../logs/update.log"
    formatter: simple
    level: DEBUG
  process_file:
    class: logging.FileHandler
    filename: "../logs/process_data.log"
    formatter: simple
    level: DEBUG
loggers:
  crawler:
    handlers: [crawler_file]
    level: DEBUG
    propagate: false
  updater:
    handlers: [updater_file]
    level: DEBUG
    propagate: false
  process_data:
    handlers: [process_file]
    level: DEBUG
    propagate: false
  newsplease:
    handlers: []  # Add this line to ignore logs from newsplease
    level: INFO
    propagate: false  # Ensure newsplease logs don't propagate to the root logger
root:
  handlers: [crawler_file, updater_file, process_file]
  level: INFO
